name: Deploy to S3 (QA)

on:
  push:
    branches:
      - qa
  workflow_dispatch:

jobs:
  deploy-s3-qa:
    runs-on: ubuntu-latest
    environment: qa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload files to S3
        run: |
          aws s3 sync ./ s3://aws-kalli/my-qa-app-bucket/ \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "node_modules/*"

      - name: Verify upload
        run: aws s3 ls s3://aws-kalli/my-qa-app-bucket/

      - name: Print environment info
        run: |
          echo "App Name: ${{ vars.APP_NAME }}"
          echo "Environment: ${{ vars.APP_ENV }}"
          echo "Deploy Env: ${{ vars.DEPLOY_ENV }}"
          echo "Log Level: ${{ vars.LOG_LEVEL }}"
